- hosts: masters[0]
  become: yes
  tasks:
   - name: install nignx-controller
     shell: helm upgrade --install ingress-nginx ingress-nginx --repo https://kubernetes.github.io/ingress-nginx --namespace ingress-nginx --create-namespace

