- hosts: masters[0]
  become: yes
  vars:
    nfs_server: "{{ ansible_eth0.ipv4.address }}"
    nfs_dir: /share
    set_default: '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
  tasks:
   - name: clone nfs provisioner
     git:
       repo: https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner.git
       dest: $HOME/nfs-subdir-external-provisioner
       clone: yes

   - name: apply rbac
     shell: kubectl create -f deploy/rbac.yaml
     args:
       chdir: $HOME/nfs-subdir-external-provisioner

   - name: edit deployment's nfs server
     replace:
       path: $HOME/nfs-subdir-external-provisioner/deploy/deployment.yaml
       regexp: '10.3.243.101'
       replace: "{{ nfs_server }}"

   - name: edit deployment's nfs directory
     replace:
       path: $HOME/nfs-subdir-external-provisioner/deploy/deployment.yaml
       regexp: '/ifs/kubernetes'
       replace: "{{ nfs_dir  }}"

   - name: apply deployment
     shell: kubectl create -f deploy/deployment.yaml
     args:
       chdir: $HOME/nfs-subdir-external-provisioner

   - name: apply storageclass
     shell: kubectl create -f deploy/class.yaml
     args:
       chdir: $HOME/nfs-subdir-external-provisioner

   - name: set storageclass as default
     shell: "kubectl patch storageclass nfs-client -p '{{ set_default }}'"

   - name: apply pvc and test-pod
     shell: kubectl create -f deploy/test-claim.yaml -f deploy/test-pod.yaml
     args:
       chdir: $HOME/nfs-subdir-external-provisioner
