- hosts: all
  become: yes
  tasks:
   - name: install packages
     yum:
       name:
        - yum-utils
        - nfs-utils
        - bash-completion
        - git
       state: present

   - name: modidfy Docker CE baseurl
     copy:
       dest: "/etc/yum.repos.d/docker-ce.repo"
       content: |
         [docker-ce-stable]
         name=Docker CE Stable - $basearch
         baseurl=https://download.docker.com/linux/centos/7/x86_64/stable
         enabled=1
         gpgcheck=1
         gpgkey=https://download.docker.com/linux/rhel/gpg
         
   - name: install packages for Docker
     yum:
       name:
        - "http://mirror.centos.org/centos/7/extras/x86_64/Packages/slirp4netns-0.4.3-4.el7_8.x86_64.rpm"
        - "http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.107-1.el7_6.noarch.rpm"
        - "http://mirror.centos.org/centos/7/extras/x86_64/Packages/fuse3-libs-3.6.1-4.el7.x86_64.rpm"
        - "http://mirror.centos.org/centos/7/extras/x86_64/Packages/fuse-overlayfs-0.7.2-6.el7_8.x86_64.rpm"
       state: present

   - name: install Docker
     yum:
       name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
       state: present
       update_cache: true

   - name: add group docker
     group:
       name: "docker"

   - name: add remote user to "docker" group
     user:
       name: "ec2-user"
       group: "docker"
       append: yes

   - name: start Docker
     service:
       name: docker
       enabled: yes
       state: started

   - name: add daemon.json to get rid of kubelet issues
     copy:
       dest: "/etc/docker/daemon.json"
       content: |
         {
           "exec-opts": ["native.cgroupdriver=systemd"],
           "log-driver": "json-file",
           "log-opts": {
             "max-size": "100m"
           },
           "storage-driver": "overlay2"
         }cd

   - name: Docker daemon reload
     shell: |
        systemctl daemon-reload
        systemctl restart docker
        systemctl enable docker

#   - name: disable SELinux
#     command: setenforce 0

   - name: disable SELinux on reboot
     selinux:
       state: disabled

   - name: Remove swapfile from /etc/fstab
     mount:
       name: swap
       fstype: swap
       state: absent

   - name: Disable swap
     command: swapoff -a
     when: ansible_swaptotal_mb > 0

   - name: set k8s config
     copy:
       dest: "/etc/modules-load.d/k8s.conf"
       content: br_netfilter

   - name: set k8s config
     copy:
       dest: "/etc/sysctl.d/k8s.conf"
       content: |
         net.bridge.bridge-nf-call-ip6tables = 1
         net.bridge.bridge-nf-call-iptables = 1

   - name: sysctl --system
     shell: sysctl --system

   - name: add Kubernetes' YUM repository
     yum_repository:
      name: kubernetes
      description: Kubernetes
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      gpgkey: 
        - https://packages.cloud.google.com/yum/doc/yum-key.gpg 
        - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      gpgcheck: yes
      enabled: yes
      exclude:
        - kubelet
        - kubeadm
        - kubectl

   - name: add CentOS7 repository - base
     yum_repository:
      name: base
      description: CentOS-7 - Base
      baseurl: http://mirror.centos.org/centos/7/os/x86_64/
      gpgcheck: no
           
   - name: add CentOS7 repository - updates
     yum_repository:
      name: updates
      description: CentOS-7 - Updates
      baseurl: http://mirror.centos.org/centos/7/updates/x86_64/
      gpgcheck: no

   - name: install kubelet
     yum:
        name: kubelet-1.21.1-0
        state: present
        update_cache: true
        disable_excludes: kubernetes

   - name: install kubeadm
     yum:
        name: kubeadm-1.21.1-0
        state: present
        disable_excludes: kubernetes

   - name: start kubelet
     service:
       name: kubelet
       enabled: yes
       state: started

- hosts: master01
  become: yes
  tasks:
   - name: install kubectl
     yum:
       name: kubectl-1.21.1-0
       state: present
       allow_downgrade: true
       disable_excludes: kubernetes
