- hosts: master
  become: yes
  tasks:
#    - name: initialize the cluster
#      shell: kubeadm init --control-plane-endpoint "master:6443" --upload-certs

    - name: create .kube directory
      file:
        path: $HOME/.kube
        state: directory
        mode: 0775 
  
    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: $HOME/.kube/config
        remote_src: yes

    - name: install calico
      shell: curl https://docs.projectcalico.org/manifests/calico.yaml -O


