- hosts: master
  become: yes
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw
  
    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"
  
  
- hosts: workers
  become: yes
  tasks:
    - name: join cluster
      shell:  "{{  hostvars['master'].join_command }}"

- hosts: master
  gather_facts: false
  tasks:
    - name: apply calico
      shell: kubectl apply -f calico.yaml

