- hosts: localhost
  become: yes
  vars:
    packages_dir: $HOME/k8s-packages
    master1: "{{ ansible_eth0.ipv4.address }}"
  tasks:
    - name: initialize the cluster
      shell: "kubeadm init --control-plane-endpoint \"{{  master1  }}:6443\" --upload-certs"

    - name: create .kube directory
      file:
        path: $HOME/.kube
        state: directory
        mode: 0775

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: $HOME/.kube/config
        remote_src: yes

    - name: apply calico
      shell: kubectl apply -f calico.yaml
      args:
        chdir: "{{ packages_dir }}"
