- hosts: localhost
  become: yes
  vars:
    packages_dir: $HOME/k8s-packages
  tasks:
   - name: install kubectl
     shell: |
        echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check
        install -o root -g root -m 0755 kubectl /usr/bin/kubectl
     args:
       chdir: "{{ packages_dir }}/k8s-packages"

   - name: create .kube directory
     file:
       path: $HOME/.kube
       state: directory
       mode: 0775

   - name: copy admin.conf to user's kube config
     copy:
       src: /etc/kubernetes/admin.conf
       dest: $HOME/.kube/config
       remote_src: yes

   - name: apply calico
     shell: kubectl apply -f calico.yaml
     args:
       chdir: "{{ packages_dir }}"
