- hosts: localhost
  become: yes
  vars:
    packages_dir: $HOME/extra-packages/kubeflow
  tasks:
   - name: install kustomize
     shell: |
        mv kustomize_3.2.0_linux_amd64 /usr/bin/kustomize       
        chmod +x /usr/bin/kustomize
     args:
       chdir: "{{ packages_dir }}"

   - name: install kubeflow
     shell: while ! kustomize build example | kubectl apply -f -; do echo "Retrying to apply resources"; sleep 10; done
     args:
       chdir: "{{ packages_dir }}/manifests"
