- hosts: localhost
  become: yes
  vars:
    packages_dir: $HOME/extra-packages/nfs-subdir-external-provisioner
    nfs_server: "{{ ansible_eth0.ipv4.address }}"
    nfs_dir: /share
    set_default: '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
  tasks:
   - name: apply rbac
     shell: kubectl create -f deploy/rbac.yaml
     args:
       chdir: "{{ packages_dir }}"

   - name: edit deployment's nfs server
     replace:
       path: "{{ packages_dir }}/deploy/deployment.yaml"
       regexp: '10.3.243.101'
       replace: "{{ nfs_server }}"

   - name: edit deployment's nfs directory
     replace:
       path: "{{ packages_dir }}/deploy/deployment.yaml"
       regexp: '/ifs/kubernetes'
       replace: "{{ nfs_dir  }}"

   - name: apply deployment
     shell: kubectl create -f deploy/deployment.yaml
     args:
       chdir: "{{ packages_dir }}"

   - name: apply storageclass
     shell: kubectl create -f deploy/class.yaml
     args:
       chdir: "{{ packages_dir }}"

   - name: set storageclass as default
     shell: "kubectl patch storageclass nfs-client -p '{{ set_default }}'"

   - name: apply pvc and test-pod
     shell: kubectl create -f deploy/test-claim.yaml -f deploy/test-pod.yaml
     args:
       chdir: "{{ packages_dir }}"
